from tree import *
from insere import *
from printOrdem import *
from busca import *
from lerDoArquivo import *
from altura import *
from removeValor import *
from utilidade import *
from cores import *
from mostraArvore import *
from menu import *
from defines import *
from balancear import *
#from _____________ import *
